declare function rconsoleclear(): ()
declare function consoleclear(): ()

declare function rconsolecreate(): ()
declare function consolecreate(): ()

declare function rconsoledestroy(): ()
declare function consoledestroy(): ()

declare function rconsoleinput(): string
declare function consoleinput(): string

declare function rconsoleprint(text: string): ()
declare function consoleprint(text: string): ()

declare function rconsolesettitle(title: string): ()
declare function consoletitle(title: string): ()
declare function rconsolename(title: string): ()